services:
  playground:
    tty: true
    restart: always
    working_dir: /workspace
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    volumes:
      - ..:/workspace:cached
      - playground-node:/workspace/node_modules

volumes:
  playground-node:
