name: linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # https://github.com/actions/setup-node?tab=readme-ov-file#supported-version-syntax
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: Use Node.js
        uses: actions/setup-node@v4 # https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install bun
        run: npm i -g bun
      - name: Install node modules
        run: bun i
      - name: Run lint
        run: bun run lint
